name: CI - clonando App y ejecutando tests

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 6007
      VITE_API_URL: http://localhost:6007/api
 
    steps:
    - name: Checkout repo actual (con el workflow)
      uses: actions/checkout@v3

    - name: Clonar repo Athena Reux Bank 
      run: |
        git clone https://github.com/engineerqajimenez-jpg/taller-playwright-atenea.git app

    - name: Crear archivos .env para el backend
      run: |
          mkdir -p redux-athena-bank/backend 
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> redux-athena-bank/backend/.env 
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> redux-athena-bank/backend/.env 
          echo "PORT=${{ env.PORT }}" >> redux-athena-bank/backend/.env 
          echo "VITE_API_URL=${{ env.VITE_API_URL }}" >> redux-athena-bank/backend/.env 

    - name: Instalar dependencias de backend
      run: |
        cd redux-athena-bank/backend 
        npm install

    - name: Construir backend
      run: |
        cd redux-athena-bank/backend
        # Usamos "start" porque es el que existe en tu package.json
        nohup npm run start > backend.log 2>&1 &
        sleep 10

    - name: Instalar wait-on
      run: npm install -g wait-on

    - name: Esperar a que el backend esté disponible
      run: npx wait-on tcp:6007 --timeout 60000 # Máximo 1 minuto

    - name: Ver logs si el backend falla
      if: failure()
      run: cat redux-athena-bank/backend/backend.log

    - name: Instalar dependencias del frontend
      run: |
        cd redux-athena-bank/frontend
        npm install

    - name: Esperar a que el frontend esté disponible
      run: wait-on http://localhost:3000
    - name: Ejecutar tests 
      run: |
        cd redux-athena-bank/frontend
        npm run test
